### ISSUE TITLE
Text formatting

### ISSUE THREAD

**Issue by diboma** [apankrat/nullboard#1]
Nice job ! Any (easy) way of adding basic text formatting (bold, italic, underline, font color, bulleted list, numbered list) ?

**Comment by apankrat** [comment]
There might be, but it's not something that I think belongs to NB.

NB is meant to replace simple pen-and-paper lists, which are typically short, sweet and flat looking. So one of the goals with the NB is to try and entice keeping notes equally succinct here as well. Hence, for example, the support for collapsing notes.

One change I was considering is adding support for color-tagging notes as whole, through just a simple fat dot at one of the note's corners. This is probably not what you are after, but it's basically the extent of fancy decoration that I think is suitable for the NB.

Hope this makes sense.

PPS. Bulleted lists _are_ supported, though in a rather minimalist way. Ctrl-Shift-8 will insert a bullet symbol followed by a space.
