### ISSUE TITLE
#hash cross link

### ISSUE THREAD

**Issue by geeohgeegeeoh** [apankrat/nullboard#10]
A second level of index/indirection is often useful. If you can work in some markup processing to maintain a db of crosslinks by #string then we can co-relate things in different lists by subtopic. 

Also by date.

(this kind of thing tends to the "you're bigging it up too much" and a WONTFIX is a fine response.

**Comment by apankrat** [comment]
Ugh, yes, I think that's a rather marginal feature (if I understand what you are suggesting correctly - basically tagging notes in some way to group them into classes across all lists on the board? And then do some sort of filtered view by tags?).

**Comment by geeohgeegeeoh** [comment]
> Ugh, yes, I think that's a rather marginal feature (if I understand what you are suggesting correctly - basically tagging notes in some way to group them into classes across all lists on the board? And then do some sort of filtered view by tags?).

Yes. thats exactly what I meant. I don't know about trello but wunderlist does this, and a work colleague swears by it. Lists are good abstractions but an alternate path of grouping as a free-set by #hash is another grouping model which would permit eg "filter to hash" and then only see entries in each kanban state on that hashtag. its bigging things up. I wouldn't do it in a hurry

**Comment by apankrat** [comment]
Yeah, that's not something that I think belongs to NB. At least not in its current state. It's basically a very niche advance us. It is very clever, granted (reminds me of how Opera Mail kept a single flat list of all emails and then each "folder" was just a filtered view into it).

I'm going to close this. For now.
