### ISSUE TITLE
Feature Request: Big Board

### ISSUE THREAD

**Issue by Cupbox** [apankrat/nullboard#23]
Hi. Kanboard has a [plugin](https://github.com/stinnux/kanboard-bigboard) that allows you to visualise all your boards on one page appended one after the other. 
This means less switching and more time saved.
While the original does not support it, it would be cool to move tasks across boards.
Thanks.

**Comment by apankrat** [comment]
Do you have a screenshot of how it looks in action?

**Comment by Cupbox** [comment]
Ripped this off an issue there
![!Big Board](https://user-images.githubusercontent.com/10849557/39451902-4af5c7e6-4c9e-11e8-8107-649cb4329483.png)

**Comment by apankrat** [comment]
So boards are just stack vertically, one after another? I can see how this can be handy for moving items between the boards, but in this particular example it's not hard to arrange all within a single board -

![big-board](https://user-images.githubusercontent.com/957994/83615283-a0c9c580-a586-11ea-9268-f2d4401b910d.png)

That's not a formal Kanban format, but functionally it's the same.

**Comment by Cupbox** [comment]
That's a pretty innovative layout though it kinda removes the whole satisfaction with seeing your Queue slowly shrink :).
I use this to simulate the Bigboard currently which works pretty well in of itself but might get bloated with time hence my request.
![2020-06-03_01-12-28](https://user-images.githubusercontent.com/13769570/83645717-53f3e800-a5a2-11ea-9efd-69365814673d.png)
