### ISSUE TITLE
Browser compatibility

### ISSUE THREAD

**Issue by zigazeljko** [apankrat/nullboard#3]
Apart from that one call to `Object.assign`, the rest of the code seems to be compatible with older browsers. Could you add a polyfill for `Object.assign` to make this app work also in older browsers?

**Comment by apankrat** [comment]
Gotta plead ignorance here. Do you know if there is any suitable substitute in jQuery for that? I suspect there might be.

**Comment by apankrat** [comment]
PS. What's browser do you use that doesn't support `Object.assign`? [MDN doesn't show](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/assign#Browser_compatibility) any mainstream ones lacking this support.

**Comment by zigazeljko** [comment]
Actually there is a substitute in jQuery, namely `$.extend` (https://api.jquery.com/jquery.extend/). You can directly substitue that `Object.assign` call like this:

```
return $.extend(new Board, board);
```

PS. I'm stuck on an older version of Chromium (version 37).

**Comment by apankrat** [comment]
OK, excellent, thanks. Will patch up as time permits.

**Comment by apankrat** [comment]
OK, resolved with https://github.com/apankrat/nullboard/commit/f84528728c06205e3bd657317a4347fc8fa1c7f3
