### ISSUE TITLE
board not visible

### ISSUE THREAD

**Issue by lordvalium** [apankrat/nullboard#45]
Hi, i have created a new board. But the new board is not visible on the other device. What can i do?

And can i set a board as default `?

**Comment by apankrat** [comment]
Nothing you can do.

No, you can't.

**Comment by lordvalium** [comment]
So its simply not possible to share a board over 2 clients as its really saved locally on my laptops browser cache?

**Comment by Hrxn** [comment]
https://github.com/apankrat/nullboard#locally-stored

**Comment by apankrat** [comment]
> So its simply not possible to share a board over 2 clients as its really saved locally on my laptops browser cache?

Not in the cache per se, but, yes, it is saved in a _local_ storage only.

**Comment by almereyda** [comment]
The progress on what you request is tracked in #2

**Comment by lordvalium** [comment]
Thats awesome @almereyda - yes thats my point. I also see nullboard better than most others. 
So sharing it (does not matter how) would be amazing
