### ISSUE TITLE
Use a readable font size

### ISSUE THREAD

**Issue by neuhaus** [apankrat/nullboard#5]
Using Windows 10 Firefox on a 24" 16:10 1920x1200 monitor I have to increase the size to 150% to get an acceptable font size.
With the default font size the _three_ columns used by the sample page use _less then half_ of my screen width.

**Comment by apankrat** [comment]
What a serendipitous coincidence. All screenshots and screencaps were made on 24" 1920x1200 monitor using Firefox for Windows, with the latter running at its stock 96 dpi setting. How did you manage to make the whole thing render in extra tiny font? Do you browse zoomed out by default?

That said, I have an item on todo list to use 'rem' settings for font-size, so this should presumably solve the complaints of things looking _too_ small.

**Comment by goldbattle** [comment]
This would really be nice to have. I just manually zoom in, but it would be nice if it could remember it on load. Maybe something like [this](https://stackoverflow.com/a/9441618) could work with a zoom plus minus button someplace?

**Comment by apankrat** [comment]
@goldbattle - "zoom" is _an_ option, but it blurs 1px lines when used.

**Comment by apankrat** [comment]
Added an option to bump up the font size by 15%.

![foo](https://pbs.twimg.com/media/ERJHyCiXUAAda2Z?format=png)
