### ISSUE TITLE
Can we have a favicon?

### ISSUE THREAD

**Issue by Hrxn** [apankrat/nullboard#52]
Straight to the facts: This is really great!

I've been looking for something like this for a long time, to be honest.

It's simple, stylish, very straightforward to use. And it works offline! Yay.

Just one question: 
This has a very nice touch and polished feel, but I think a favicon, even a very simple one embedded into the HTML, would really round off the overall look.

Let me know what you think.

**Comment by apankrat** [comment]
Yep, will add shortly.

**Comment by apankrat** [comment]
Done.

https://nullboard.io/extras/favicon-16.png

**Comment by Hrxn** [comment]
Thanks, I like that one actually!

But wouldn't 32x32px be better? For HiDPI display support? Not sure how such an 16px icon would look there.
