### ISSUE TITLE
Where is the nullboard agent source code?

### ISSUE THREAD

**Issue by raphael-louis-andress** [apankrat/nullboard#60]
Hi all! 

So... where is the nullboard agent source code?

> The data can also be automatically backed up to a local disk (with the help of [Nullboard Agent](https://nullboard.io/backups)).

#### reference
- https://nullboard.io/backups

**Comment by apankrat** [comment]
Most of it is in https://github.com/apankrat/nullboard-agent

**Comment by raphael-louis-andress** [comment]
@apankrat Hi! How are you? thank you for feedback ;D
