### ISSUE TITLE
Can't open my NB in another browser

### ISSUE THREAD

**Issue by stacy-c** [apankrat/nullboard#7]
Nullboard is great, I am really finding it useful.

Pardon my ignorance here, but I tried to open my nullboard file (renamed index.html) in a different browser and it does not show my edits. I assume this is due to Local Storage in the browser where I made the edits, and the other browser has no access to that data? 

Is there a way to carry my edits over to a different browser? Export/import the board?

Thank you!

**Comment by apankrat** [comment]
> I assume this is due to Local Storage in the browser where I made the edits, and the other browser has no access to that data?

That's exactly it.

> Export/import the board?

Yes, correct as well. Export into a file, save it somewhere, then import in your second browser.

**Comment by bonnebulle** [comment]
A cool Feature should be to export.backup all boards at once...
I dont know if it's possible (easy to implement)

Me I realy like the current file's backuping system (cloudless)
A batch cool help for travelers like me (;
