### ISSUE TITLE
List width not restored on load

### ISSUE THREAD

**Issue by tlaugier** [apankrat/nullboard#71]
Hi!

First of all thanks for this brilliant app!

I like to have quite large lists and I noticed that this UI setting is not restored between sessions/load of the page.

STR: 
1. Modify the list width to a non default value using the UI preferences button
2. Close the tab
3. Open nullboard in a new browser tab

ER:
The list width is the same as before the tab was closed

AR:
The list width is back to the default value

**Comment by justinpchang** [comment]
+1, I run in to this issue a lot as well. The above PR should fix it
