### ISSUE TITLE
Support full width

### ISSUE THREAD

**Issue by JensPiegsa** [apankrat/nullboard#8]
Great effort! One quick suggestion: currently lists on a board wrap every fourth column. In case this isn't a conceptual thing, it would be nice if a board could leverage the full width of a browser window on larger screens.

**Comment by apankrat** [comment]
Noted. This will require a rework of the layout, but the fact that lists _wrap_ was never a good thing to begin with. There should be a horizontal scroll instead.

**Comment by apankrat** [comment]
OK, this is should be resolved now with https://github.com/apankrat/nullboard/commit/a6959988a3d1670a9ba5c4ae603e3de0bd9a28c1

Works something like this - https://dribbble.com/shots/6610142-Nullboard-Crowded-Mode
