### ISSUE TITLE
Documentation link

### ISSUE THREAD

**Issue by 7heo** [apankrat/nullboard#81]
Hello, I would have opened a PR against the repository for the [nullboard.io](https://nullboard.io/) website, but I didn't find it. It might not even exist (I heard of people editing HTML by hand! -gasp-).

Anyway, [the link for the "source code"](https://github.com/apankrat/nullboard/blob/master/nullboard.html) in the "remote backups" section of the [Nullboard backups documentation page](https://nullboard.io/backups) points at the entire 5172 SLOCS source file for nullboard, with written a description of where to find the relevant part. I would suggest making it [a more specific link](https://github.com/apankrat/nullboard/blob/master/nullboard.html#L2469-L2550) instead, with the relevant code portion highlighted.

HTH.

**Comment by apankrat** [comment]
Patched it, thanks.

**Comment by apankrat** [comment]
> I heard of people editing HTML by hand!

This is the way.
