### ISSUE TITLE
Nullboard not saving boards, cards, or notes

### ISSUE THREAD

**Issue by Wiserrhino** [apankrat/nullboard#82]
Yesterday, I set up a beginning kanban with nullboard and this morning when I open it up again (at localhost) nothing was saved.

I'm using apache2 on linux. Are there folder permissions that I need to set? Is it something I failed to do, like click "save" somewhere?

Thanks.

**Comment by rpavlik** [comment]
it's entirely stored in your browser (local storage), there is no server component. I don't even use a server, I just open the htm with a browser.
