### ISSUE TITLE
Express.js port of nullboard-agent for Mac/Linux local backup

### ISSUE THREAD

**Issue by justinpchang** [apankrat/nullboard#83]
Hi, all. I've ported nullboard-agent to Express.js. It's a lightweight web server that can be run in the background and act as the local backup server for any nullboard instance. This allows us to run auto-backup on non-Windows computers.

Currently, the server does not respect the max undo length. I believe the original C++ server does not either.

Installation instructions are in the repo for any that are interested. Contributions welcome!

https://github.com/justinpchang/nullboard-agent-express

**Comment by justinpchang** [comment]
If appropriate, I'd be happy to add a reference in this repo's README as well

**Comment by apankrat** [comment]
OK, done. I'll do a quick post on Twitter next.

**Comment by justinpchang** [comment]
Tw@jpchanggg
