### ISSUE TITLE
comment

### ISSUE THREAD

**Issue by jaygray0919** [apankrat/nullboard#9]
have tried many alternatives over the years
currently use 3x5 cards because alternatives are too clunky (why does anyone use MS OneNote?)
have switched over to NB and luv it
still use 3x5 cards (kept in jacket/shirt pocket, etc.) as pencil+paper is still the least obtrusive note-taking mechanism, especially when mobile/desktop is difficult/inappropriate
then xfer paper notes to NB
NB and 3x5 is the best solution i've found during 20+ years of taking notes
TY!

**Comment by apankrat** [comment]
Thank you, Jay! Very kind :)
